apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8stest
  region: eu-west-1
#vpc:
#  id: "vpc-40537c24"
#  subnets:
#    private:
#        eu-west-1a: { id: "subnet-037f36a0494a296c1" }
#        eu-west-1b: { id: "subnet-70586b06" }
#        eu-west-1c: { id: "subnet-5b2b5303" }
#  clusterEndpoints:
#    publicAccess:  true
#    privateAccess: true

nodeGroups:
  - name: ng1-1a
    instanceType: t3a.medium
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 20
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
    ssh:
      publicKeyName: 'eks'
    availabilityZones:
    - eu-west-1a
  - name: ng1-1b
    instanceType: t3a.medium
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 20
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
    ssh:
      publicKeyName: 'eks'
    availabilityZones:
    - eu-west-1b
  - name: ng1-1c
    instanceType: t3a.medium
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 20
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
    ssh:
      publicKeyName: 'eks'
    availabilityZones:
    - eu-west-1c
